/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.Controller.CategoryController;
import edu.ijse.dto.CategoryDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dimuthu
 */
public class CategoryView extends javax.swing.JFrame {

    private CategoryController categoryController;

    /**
     * Creates new form CategoryView
     */
    public CategoryView() {
        initComponents();
        categoryController = new CategoryController();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCategoryId = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        btnAddCategory = new javax.swing.JButton();
        btnUpdateCategory = new javax.swing.JButton();
        btnDeleteCategory = new javax.swing.JButton();
        txtCategoryId = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categories");

        lblCategoryId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategoryId.setText("Category ID");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategory.setText("Category");

        btnAddCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddCategory.setText("Add");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        btnUpdateCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateCategory.setText("Update");
        btnUpdateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCategoryActionPerformed(evt);
            }
        });

        btnDeleteCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteCategory.setText("Delete");
        btnDeleteCategory.setToolTipText("");
        btnDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCategoryActionPerformed(evt);
            }
        });

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblCategoryId)
                        .addGap(35, 35, 35)
                        .addComponent(txtCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategory)
                                .addGap(37, 37, 37)
                                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddCategory)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateCategory)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteCategory))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(lblCategoryId)
                    .addComponent(txtCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCategory)
                    .addComponent(btnUpdateCategory)
                    .addComponent(btnDeleteCategory))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        // TODO add your handling code here:
        saveCategory();
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void btnDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCategoryActionPerformed
        // TODO add your handling code here:
        deleteCategory();
    }//GEN-LAST:event_btnDeleteCategoryActionPerformed

    private void btnUpdateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCategoryActionPerformed
        // TODO add your handling code here:
        updateCategory();
    }//GEN-LAST:event_btnUpdateCategoryActionPerformed

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
        // TODO add your handling code here:
        searchCategory();
    }//GEN-LAST:event_tblCategoryMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnDeleteCategory;
    private javax.swing.JButton btnUpdateCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCategoryId;
    private javax.swing.JTable tblCategory;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCategoryId;
    // End of variables declaration//GEN-END:variables
private void clearForm() {
        txtCategoryId.setText("");
        txtCategory.setText("");
    }

    private void saveCategory() {
        try {
            CategoryDto categoryDto = new CategoryDto(txtCategoryId.getText(), txtCategory.getText());
            String response = categoryController.save(categoryDto);
            JOptionPane.showMessageDialog(this, response);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at Save Data.");
            e.printStackTrace();
            clearForm();
        }
    }

    private void updateCategory() {
        try {
            CategoryDto categoryDto = new CategoryDto(txtCategoryId.getText(), txtCategory.getText());
            String response = categoryController.update(categoryDto);
            JOptionPane.showMessageDialog(this, response);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at Update Data.");
            e.printStackTrace();
            clearForm();
        }
    }

    private void deleteCategory() {
        try {
            String categoryId = txtCategoryId.getText();
            String response = categoryController.delete(categoryId);
            JOptionPane.showMessageDialog(this, response);
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at Delete Data");
        }
    }

    private void searchCategory() {
        try {
            String categoryId = tblCategory.getValueAt(tblCategory.getSelectedRow(), 0).toString();
            CategoryDto categoryDto = categoryController.get(categoryId);
            if (categoryDto != null) {
                txtCategoryId.setText(categoryDto.getCategoryId());
                txtCategory.setText(categoryDto.getCategoryName());
            } else {
                JOptionPane.showMessageDialog(this, "Category not Found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at Loading data");
            e.printStackTrace();
        }

    }

    private void loadTable() {
        try {
            String[] columns = {"Category ID", "Category"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblCategory.setModel(dtm);

            ArrayList<CategoryDto> categoryDtos = categoryController.getAll();
            for (CategoryDto categoryDto : categoryDtos) {
                Object[] rawData = {categoryDto.getCategoryId(), categoryDto.getCategoryName()};
                dtm.addRow(rawData);
            }

        } catch (Exception e) {

        }
    }
}
